annotations:
  artifacthub.io/category: database
  artifacthub.io/changes: |-
    - kind: changed
      description: '[redis] Fix appVersion set to `v8.8.8` instead of `v8.8.0` (#1374)'
      links:
      - name: Pull Request
        url: https://github.com/CloudPirates-io/helm-charts/pull/1374
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: Redis
      url: https://redis.io
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/redis
    - name: Application
      url: https://github.com/redis/redis
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  license: Apache-2.0
apiVersion: v2
appVersion: 8.8.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/cloudpirates
  version: 2.2.0
description: An open source, in-memory data structure store used as a database, cache,
  and message broker.
home: https://www.redis.io
icon: https://a.storyblok.com/f/143071/512x512/32c74816d1/redis-logo.svg
keywords:
- redis
- database
- cache
- in-memory
- key-value
- nosql
maintainers:
- email: hello@cloudpirates.io
  name: CloudPirates GmbH & Co. KG
  url: https://www.cloudpirates.io
name: redis
sources:
- https://github.com/CloudPirates-io/helm-charts/tree/main/charts/redis
- https://github.com/redis/redis
type: application
version: 0.30.3
